require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

